version: "3.7"

services:
    foundry:
        image: felddy/foundryvtt:9.255.0
        environment:
            FOUNDRY_USERNAME:
            FOUNDRY_PASSWORD:
            FOUNDRY_ADMIN_KEY:
            CONTAINER_PRESERVE_CONFIG:
            FOUNDRY_UID:
        hostname: ${FOUNDRY_HOSTNAME}
        ports:
            - "${EXPOSED_FOUNDRY_PORT}:30000/tcp"
        restart: always
        volumes:
            - ${FOUNDRY_DATA_VOLUME}:/data

    fvttoptimizer:
        build: python
        volumes:
            - ${FOUNDRY_DATA_VOLUME}:/app

    node:
        build: node
        environment:
            TINY_PNG_API_KEY:
            IMAGE_FILE_GLOB:
            COMPRESSED_IMAGE_CACHE_FILE:
            COMPRESS_WITH_TINY_PNG:
        init: true
        volumes:
            - ../../:/app
        working_dir: /app
